#!/bin/bash

set -eu

mkdir -p /var/backups/gp/passbolt/var/www/passbolt/config/gpg \
         /var/backups/gp/passbolt/var/www/passbolt/webroot/img/public
rsync -a --delete /var/www/passbolt/config/gpg/          /var/backups/gp/passbolt/var/www/passbolt/config/gpg/
rsync -a --delete /var/www/passbolt/webroot/img/public   /var/backups/gp/passbolt/var/www/passbolt/webroot/img/public
